// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace API.Models
{
    public partial class Marathon_Form
    {
        [Key]
        public int Record_ID { get; set; }
        [Required]
        [StringLength(100)]
        public string Full_Name { get; set; }
        [Column(TypeName = "date")]
        public DateTime Date_Of_Birth { get; set; }
        public bool Gender { get; set; }
        [Required]
        [StringLength(250)]
        public string Address { get; set; }
        [StringLength(20)]
        public string Phone_Number { get; set; }
        [StringLength(50)]
        public string Email_Address { get; set; }
        [Column(TypeName = "time(0)")]
        public TimeSpan From_Time { get; set; }
        [Column(TypeName = "time(0)")]
        public TimeSpan To_Time { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal Distance { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created_Time { get; set; }
        [Required]
        [StringLength(50)]
        public string Created_By { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Updated_Time { get; set; }
        [StringLength(50)]
        public string Updated_By { get; set; }
        public bool Status { get; set; }
    }
}